version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - MESSAGE=${MESSAGE:-Hello World}

  frontend:
    build: ./frontend
    ports:
      - "5500:80"
    depends_on:
      - backend